### ISSUE TITLE
OAuth support in loader.py

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#12]
Accessing private CartoDB tables will require OAuth support in loader.py. I forked the CartoDB Python client which we can modify as needed:

https://github.com/MapofLife/cartodb-python

**Comment by gaurav** [comment]
One last thing left here: cartodb-python uses oauth2, which bizarrely does not support Unicode. This pull request seems like it'd fix things: https://github.com/simplegeo/python-oauth2/pull/91, but I'm reluctant to add more code into this project unless we have to. Tonight, I'm going to try to get https://github.com/tweepy/python-oauth2 to work for us; it's much more recently-modified (i.e. better maintained) code.

**Comment by gaurav** [comment]
Unfortunately, tweepy's python-oauth2 has the same version or module name as the simplegeo one, so they overwrite each other, and use a different API. Fun times! I'm going to close this until we get POST working. Once that's done, if the Unicode issues still persist, I'll reopen this. The Unicode issues are covered by issue #10 anyway.

**Comment by eightysteele** [comment]
Reopening because I don't want to forget about this. :) We'll need OAuth support for accessing private tables. Does unicode support in OAuth matter though? Does OAuth touch data or is it just for authentication?

**Comment by gaurav** [comment]
We _have_ OAuth support, we just don't have a well-mainted OAuth library we can use.

CartoDB (like everybody else) uses https://github.com/simplegeo/python-oauth2, which hasn't been updated since May, and which has a huge number of people submitting fixes to what looks like exactly the UTF-8 bug affecting us. Unfortunately, nobody seems to have properly forked python-oauth2 (every fork I looked at used the same namespace, 'oauth2', even where it changes the API for this module, and every one used the same version number, for bonus confusion points). 

Most other developers (e.g. Google) appear to just be incorporating the module into their codebase, then modifying it for their own use (and to get rid of bugs like the UTF-8 issue). Is there an easy way to insert the OAuth codebase into cartodb-python? Otherwise, we'll just have to bite the bullet and (properly) fork python-oauth2 into github.com/mapoflife.
