### ISSUE TITLE
loader.py bulkloading to CartoDB

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#13]
Right now loader.py produces a GeoJSON document per source which can be manually uploaded to CartoDB. We'll want to automate this by bulkloading directly to CartoDB from loader.py. There are a couple of options here:

http://support.cartodb.com/discussions/questions/14-importexport-api

**Comment by gaurav** [comment]
I wonder if it's feasible to upload the GeoJSON document directly to CartoDB, as an HTML form upload, then screen-scrape to figure out which table it was saved as? Probably not, unless CartoDB's planned import/export API gets pushed further into the future.

Also, this might possible be unnecessary if it's easier to COPY the data directly into the underlying PostgreSQL database once we have our own internal CartoDB instance.

**Comment by gaurav** [comment]
This is now mostly done, barring a bunch of bugs which may or may not be due to the internet connection (so not quite ready to close, but substantially ready). There is also issue #24 to figure out.

One last thing we need to get working is to get it uploading to moldb.io. I've started work on this by using our fork of cartodb-python [as of @cd100aac3f1](https://github.com/MapofLife/cartodb-python/commit/cd100aac3f1853319c836c5d3c931689e71ae6a1), which now supports entering a different domain name.

However, afaict, Vizz isn't actually using the CartoDB API in the source code - it seems to me that they have a separate application handling API calls, which is this: https://github.com/Vizzuality/CartoDB-SQL-API

@eightysteele: Could you check with your contacts at Vizz and see if this is the case? That'd be a lot faster than putting in a bug report or Twitter. If this is true, could you set this up on our server? Or should we use the built-in API?

**Comment by eightysteele** [comment]
Yeah, CartoDB uses this module for servicing SQL API calls: https://github.com/Vizzuality/CartoDB-SQL-API

**Comment by gaurav** [comment]
The inability to use POST (instead of GET) has now been pushed to Vizz: http://support.cartodb.com/discussions/problems/84-postgresql-doesnt-log-in-properly-through-the-sql-api-when-using-post

The moldb.io is showing what appears to be this exact bug on both POST and GET requests; with any luck, Vizz will report that this was a configuration problem, Aaron is reconfigure moldb.io, and we're good to go.

**Comment by eightysteele** [comment]
> The inability to use POST (instead of GET) has now been pushed to Vizz: http://support.cartodb.com/discussions/problems/84-postgresql-doesnt-log-in-properly-through-the-sql-api-when-using-post

+1

**Comment by gaurav** [comment]
We _can_ definitely bulk-load to our local CartoDB server. We still have lots of bugs, but those are covered in separate bugs. I don't think there's anything still waiting to be done for this issue which isn't covered by another issue, so I'm closing this one.
