### ISSUE TITLE
Info window clicks

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#29]
Clicking on a point or polygon infowindow creates a major disturbance in the force.

**Comment by jmalczyk** [comment]
After including some cartodb css and adding an id to the map container, this is working. However, if the map is zoomed out so far that more than 360 degrees of longitude are visible, the info box will appear above the feature closest to the center of the viewport instead of the one clicked on. This is due to a bug in the cartodb-gmapsv3 client. We probably should limit the viewport to 360 degrees anyway.
