### ISSUE TITLE
scientificname = '=Scientific name' in point table

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#46]
I noticed that the `scientificname` column in the points table on CartoDB has a bunch of `=Scientific name` values.

``` sql
select count(*) from points where scientificname = '=Scientific name'
#9271
```

Maybe something wonky going on with `loader.py`.

**Comment by gaurav** [comment]
D'oh. It's an incorrect entry in the config file.

**Comment by gaurav** [comment]
Should be fixed now!

At some point, we're probably going to want some sort of tabular interface to MoL as well, which can ask questions like "how many species named X are available, and from which datasets". Not sure if that should go into the frontend (i.e. app/) or into the backend (i.e. workflow/). Either way, this will be helpful for me with issue #26, and probably of much interest to our users, too.

**Comment by eightysteele** [comment]
> how many species named X are available, and from which datasets

This seems like an ideal query for CartoDB, yeah? We can definitely answer the above question using `UNION SELECT` queries across our tables. If there's a need to surface this functionality on the UI, let's submit a separate issue for it. Maybe?

**Comment by eightysteele** [comment]
@gaurav: How did you fix this issue on the points table? It's not responding to SQL or map queries now so I'm trying to debug.

**Comment by gaurav** [comment]
I just deleted that collection and reuploaded it, with the DBF mapping fixed in config.yaml.

Hmm, that's probably because I'm uploading GBIF data into the points table. Simon Tokumine suggested that time-consuming operations might be failing for us because of the load on our instance from all the data uploads.

Check if the situation is any better now: we're now down to a single upload, since issue #48 prevents me from restarting either the rangemap or Cody's upload. If the situation is still the same, I could turn off GBIF upload for now if that'd help.

**Comment by eightysteele** [comment]
> I just deleted that collection and reuploaded it, with the DBF mapping fixed in config.yaml.

If you deleted the `points` table and then recreated it, I know what's happening. My indexes got blasted! :)

No need to stop the GBIF upload for now.

**Comment by eightysteele** [comment]
Resolved.
