### ISSUE TITLE
Optimize layer extent calculations

### ISSUE THREAD

**Issue by eightysteele** [MapofLife/MOL#76]
For optimizing layer zoom to extent in #61, we either need to upldate loader.py to start populating minx, miny, maxx, maxy or add a new column to the points and polygons tables with `ST_EXTENT` precalculated.

**Comment by gaurav** [comment]
Since it sounds like we're going to be reuploading everything anyway, the best way to do this is probably through Shapely (our upload script converts the geometry into a a Shapely.geometry object right before upload): http://toblerity.github.com/shapely/manual.html

**Comment by gaurav** [comment]
Done in @8850c5277b00b7. I've set minx, miny, maxx and maxy as `DOUBLE PRECISION` data in PostgreSQL (through the MoL Field Specification); however, PostGIS uses `float4`s instead of `float8`s to store the bounding box (see http://postgis.refractions.net/documentation/manual-1.4/ST_Envelope.html); they say it's easier to index. So maybe we should reduce precision on our end, too? We'll have to be careful about rounding so as to always completely enclose the polygon, though.

Anyway, I compared Shapely's output (which we're using) with PostGIS's for a few entries, and it seems to be working correctly!

**Comment by eightysteele** [comment]
7 decimals is what we want. Good stuff!

**Comment by gaurav** [comment]
For now, I'm turning this off so we don't need to change the database schema. But all the code is in! You just need to undo commit @c8f3a70.

**Comment by eightysteele** [comment]
On the UI side right now we're sending an extent query to CDB and caching results. Closing issue.
