### ISSUE TITLE
Search UI: clear up search/filter area after mapping

### ISSUE THREAD

**Issue by walterj** [MapofLife/MOL#94]
After 'map layers' button has been pushed, make disappear the four windows below search (Names, Sources, Types, Results) and clear the name in the search text box.

**Comment by eightysteele** [comment]
Yeah, so I'm not in favor of this because it causes the UI to behave unexpectedly. The search results UI should only be closed and cleared if a user explicitly does so. When the UI starts "doing things for you to be helpful", it's helpful for maybe 10% of users, and annoys the remaining 90% because it does something they didn't expect.

Does this make sense?

So I'm thinking that we should leave this issue open, and then revisit it if MOL users start commenting on it or submitting new issues that are related.
